# interfaces para monitorizar
packetbeat.interfaces.device: any
packetbeat.flows:
  timeout: 30s
  period: 10s

# protocolos a analizar
packetbeat.protocols.http:
  ports: [80]
  send_headers: true
  send_all_headers: true
packetbeat.protocols.dns:
  ports: [53]
  include_authorities: true
  include_additionals: true
packetbeat.protocols.tls:
  ports: [443,5601]
  send_certificates: false
packetbeat.protocols.mysql:
  ports: [3306]
packetbeat.protocols.dhcp:
  ports: [67]
packetbeat.protocols.icmp:
  enabled: true

# procesamiento de datos
processors:    
      - add_tags:
          tags: [traffic]
          target: "datatype"

# Configuracion de salida de logs
output.logstash:
  hosts: ["elk.proyectoASIR.local:4405"]
  ssl.enabled: true
  ssl.certificate_authorities: ["/usr/share/packetbeat/SSL/ca.crt"]
  ssl.certificate: "/usr/share/packetbeat/SSL/client.crt"
  ssl.key: "/usr/share/packetbeat/SSL/client.key"

